<div class="container">
<div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-10">
    <h3><b>Berdasarkan Peraturan Walikota Nomor 60 Tahun 2016 Tentang Tugas Pokok
Dan Rincian Tugas Unit Dinas Sosial Kota Tasikmalaya</b></h3>
<p > <h1 style="text-align: center;"><b>Tugas Pokok dan Fungsi</h1></p>
<p ><b> <h4 style="text-align: left; text-indent: 0.7in;">Bagian Ke satu : Kepala Dinas Sosial</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Kepala Dinas mempunyai tugas pokok merumuskan sasaran, mengarahkan, menyelenggarakan,  </h4></p>
<p > <h4 style="text-align: left; text-indent: 0.9in;">membina, mengoordinasikan,mengendalikan, mengevaluasi dan melaporkan program kerja dinas.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Kepala Dinas :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. menyelenggarakan penyusunan rencana program kerja dinas</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. merumuskan dan menetapkan visi dan misi serta rencana strategik dan program kerja dinas untuk</h4></p>
<p > <h4 style="text-align: left; text-indent: 1.0in;"> mendukung visi dan misi daerah;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. menyelenggarakan perumusan dan penetapan kebijakan teknis operasional di bidang sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. menyelenggarakan pengoordinasian pelaksanaan kegiatan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. menyelenggarakan pembinaan dan mengarahkan semua kegiatan satuan organisasi dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan koordinasi dengan Organisasi Perangkat Daerah atau Unit Kerja lain yang </h4></p>
<p > <h4 style="text-align: left; text-indent: 0.9in;">terkait untuk kelancaran pelaksanaan tugas dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. memberikan saran dan pertimbangan kepada Walikota dalam penyelenggaraan tugas pembangunan </h4><p>
<p > <h4 style="text-align: left; text-indent: 0.9in;"> dan tugas umum pemerintahan di bidang sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan monitoring, evaluasi dan pelaporan hasil pelaksanaan tugas kepada Walikota melalui <h4></p>
<p > <h4 style="text-align: left; text-indent: 0.9in;">Sekretaris Daerah; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan tugas kedinasan lain yang diberikan oleh Walikota sesuai dengan bidangnya.</h4></p>

<p ><b> <h4 style="text-align: left; text-indent: 0.7in;">Bagian Kedua : Sekretariat</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 5</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Sekretariat mempunyai tugas pokok menyelenggarakan pelayanan administrasi, koordinasi dan 
<p > <h4 style="text-align: left; text-indent: 0.8in;">pengendalian dalam pelaksanaan kegiatan ketatausahaan yang meliputi pengelolaan kepegawaian, 
<p > <h4 style="text-align: left; text-indent: 0.8in;">keuangan, umum serta perencanaan, evaluasi dan pelaporan.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Sekretariat :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. menyelenggarakan penyusunan rencana program kerja Sekretariat;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. mengoordinasikan penyusunan rencana program kerja Dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. mengelola administrasi kepegawaian, keuangan, ketatausahaan, dan kerumahtanggaan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. menyelenggarakan pembinaan dan pengembangan kelembagaan, pelayanan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">publik dan ketatalaksanaan di lingkungan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. menyiapkan rancangan peraturan dan ketentuan lainnya di bidang sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. menyelenggarakan pengelolaan data statistik di bidang sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. mengoordinasikaan evaluasi dan pelaporan pelaksanaan program kerja dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan pemantauan, evaluasi dan laporan yang berkaitan dengan tugas Sekretariat;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">j. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">(3) Sekretariat membawahkan :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. Sub Bagian Umum dan Kepegawaian;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. Sub Bagian Keuangan; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. Sub Bagian Perencanaan, Evaluasi dan Pelaporan.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 6</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Sub Bagian Umum dan Kepegawaian mempunyai tugas pokok melaksanakan pengelolaan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">perlengkapan, rumah tangga, ketatausahaan dan perpustakaan, pengelolaan administrasi 
<p > <h4 style="text-align: left; text-indent: 0.9in;">kepegawaian, serta pengembangan kelembagaan, ketatalaksanaan dan pelayanan publik.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Sub Bagian Umum dan Kepegawaian :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Sub Bagian Umum dan Kepegawaian;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. melaksanakan ketatausahaan di lingkungan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. melaksanakan pengelolaan perpustakaan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan pengurusan kerumahtanggaan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. melaksanakan pengelolaan barang milik daerah di lingkungan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. mengelola kepegawaian di lingkungan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan penyiapan bahan pembinaan dan pengembangan kelembagaan, ketatalaksanaan dan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">pelayanan publik di lingkungan dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan pemantauan, evaluasi dan laporan yang berkaitan dengan tugas Sub Bagian Umum dan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Kepegawaian;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">j. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 7</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Sub Bagian Keuangan mempunyai tugas pokok melaksanakan pengelolaan administrasi keuangan.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Sub Bagian Keuangan :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Sub Bagian keuangan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. melaksanakan penatausahaan keuangan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. melaksanakan pembinaan penatausahaan keuangan di lingkungan Dinas;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan pemantauan, evaluasi dan laporan yang berkaitan dengan tugas Sub Bagian Keuangan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 8</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Sub Bagian Perencanaan, Evaluasi dan Pelaporan mempunyai tugas pokok mengoordinasikan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">penyusunan rencana kerja, evaluasi dan pelaporan kegiatan dinas.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Sub Bagian Perencanaan, Evaluasi dan Pelaporan:</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Sub Bagian Perencanaan, Evaluasi dan Pelaporan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. menyiapkan bahan penyusunan program kerja dinas</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. menyusun bahan evaluasi dan pelaporan program kerja dinas</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan penyusunan rencana anggaran;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. mengoordinasikan penyusunan data statistik yang berhubungan dengan bidang sosial, 
<p > <h4 style="text-align: left; text-indent: 0.9in;">ketenagakerjaan dan transmigrasi;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan penyajian informasi dan data statistik berhubungan dengan bidang sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan pengelolaan data base pengembangan sistem informasi sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan pemantauan, evaluasi dan laporan yang berkaitan dengan tugas Sub 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Bagian Perencanaan, Evaluasi dan Pelaporan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">j. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b> <h4 style="text-align: left; text-indent: 0.7in;">Bagian ketiga : Bidang Pemberdayaan Sosial</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 9</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Bidang Pemberdayaan Sosial mempunyai tugas pokok mengoordinasikan perumusan bahan kebijakan, 
<p > <h4 style="text-align: left; text-indent: 0.9in;">pelaksanaan kebijakan dan pembinaan di bidang pemberdayaan sosial.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Bidang Pemberdayaan Sosial :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. menyelenggarakan penyusunan rencana program kerja bidang pemberdayaan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. menyelenggarakan penyusunan bahan perumusan kebijakan operasional pemberdayaan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. menyelenggarakan penyusunan bahan operasional, fasilitasi dan rekomendasi pelaksanaan usaha 
<p > <h4 style="text-align: left; text-indent: 0.9in;">dan kegiatan bidang pemberdayaan sosial</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. menyelenggarakan pemberdayaan penyandang masalah kesejahteraan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. menyelenggarakan pengembangan potensi sumber kesejahteraan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. menyelenggarakan pemeliharaan taman makam pahlawan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan tugas 
<p > <h4 style="text-align: left; text-indent: 0.9in;">pembinaan kesejahteraan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">(3) Bidang Pemberdayaan Sosial membawahkan :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. Seksi Pemberdayaan Penyandang Masalah Kesejahteraan Sosial (PMKS); dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. Seksi Pemberdayaan Potensi Sumber Kesejahteraan Sosial (PSKS).</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 10</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Seksi Pemberdayaan Penyandang Masalah Kesejahteraan Sosial (PMKS) mempunyai tugas pokok 
<p > <h4 style="text-align: left; text-indent: 0.9in;">menyiapkan bahan kebijakan operasional, pelaksanaan kebijakan serta pembinaan penyandang 
<p > <h4 style="text-align: left; text-indent: 0.9in;">masalah kesejahteraan sosial (PMKS).</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Seksi Pemberdayaan Penyandang Masalah Kesejahteraan Sosial (PMKS):</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Seksi Pemberdayaan Penyandang 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Masalah Kesejahteraan Sosial (PMKS);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. melaksanakan penyiapan bahan perumusan kebijakan operasional pemberdayaan penyandang 
<p > <h4 style="text-align: left; text-indent: 0.9in;">masalah kesejahteraan sosial (PMKS);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. melaksanakan pengembangan dan pengelolaan tempat penampungan Penyandang Masalah 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Kesejahteraan Sosial (PMKS);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan bimbingan dan pemberdayaan bagi PMKS;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. melaksanakan rujukan warga binaan kepada lembaga pelayanan pemerintah;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan penyiapan fasilitasi usaha kesejahteraan sosial serta bantuan bagi PMKS;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Seksi Pemberdayaan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Penyandang Masalah Kesejahteraan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 11</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Seksi Pemberdayaan Potensi Sumber Kesejahteraan Sosial (PSKS) mempunyai tugas menyiapkan bahan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">kebijakan operasional, pelaksanaan kebijakan serta pembinaan potensi sumber kesejahteraan sosial 
<p > <h4 style="text-align: left; text-indent: 0.9in;">(PSKS).</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Seksi Pemberdayaan Potensi Sumber Kesejahteraan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Sosial (PSKS):</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Seksi Pemberdayaan Potensi Sumber Kesejahteraan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Sosial (PSKS);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. melaksanakan penyiapan bahan perumusan kebijakan operasional pemberdayaan potensi sumber 
<p > <h4 style="text-align: left; text-indent: 0.9in;">kesejahateraan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. melaksanakan pengumpulan dan pengelolaan data PSKS;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan bimbingan dan pemberdayaan Pemberdayaan Potensi Sumber Kesejahteraan Sosial 
<p > <h4 style="text-align: left; text-indent: 0.9in;">(PSKS);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. melaksanakan fasilitasi bantuan teknis bagi PSKS;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan pembinaan lembaga konsultasi kesejahteraan keluarga (LK3);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan penyiapan bahan rekomendasi penerbitan ijin pengumpulan sumbangan dalam Daerah;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan pemeliharaan taman makam pahlawan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Seksi Pemberdayaan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Potensi Sumber Kesejahteraan Sosial (PSKS):</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">j. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">k. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b> <h4 style="text-align: left; text-indent: 0.7in;">Bagian Keempat : Bidang Rehabilitasi Sosial</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 12</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Bidang Rehabilitasi Sosial mempunyai tugas pokok mengoordinasikan perumusan bahan kebijakan, 
<p > <h4 style="text-align: left; text-indent: 0.9in;">pelaksanaan kebijakan dan pembinaan di bidang rehabilitasi sosial.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Bidang Rehabilitasi Sosial:</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. menyelenggarakan penyusunan rencana program kerja Bidang Rehabilitasi Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. menyelenggarakan penyusunan bahan perumusan kebijakan yang berkenaan dengan Bidang
<p > <h4 style="text-align: left; text-indent: 0.9in;"> Rehabilitasi Sosial bagi PMKS;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. mengoordinasikan pengumpulan dan pengelolaan data PMKS;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. mengoordinasikan penyelenggaraan bimbingan dan rehabilitasi sosial bagi penyandang cacat, 
<p > <h4 style="text-align: left; text-indent: 0.9in;">tuna sosial, korban Napza dan zat adiktif lainnya, tuna eks napi, anak nakal, anak terlantar, 
<p > <h4 style="text-align: left; text-indent: 0.9in;">anak jalanan, remaja putus sekolah, korban tindak kekerasan dan perlakuan salah;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. menyelenggarakan kerjasama atau kemitraan dalam pelaksanaan rehabilitasi sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Bidang Rehabilitasi Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">(3) Bidang Bidang Rehabilitasi Sosial, membawahkan :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. Seksi Rehabilitasi Anak, Remaja, Lanjut Usia dan ODK;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. Seksi Rehabilitasi Tuna Sosial dan Nafza.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 13</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Seksi Rehabilitasi Anak, Remaja, Lanjut Usia dan ODK mempunyai tugas pokok menyiapkan bahan 
<p > <h4 style="text-align: left; text-indent: 0.8in;">kebijakan operasional, pelaksanaan kebijakan serta pembinaan bagi rehabilitasi anak, remaja, lanjut 
<p > <h4 style="text-align: left; text-indent: 0.8in;">usia dan orang dengan kedisabilitasan.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Seksi Rehabilitasi Anak, Remaja, Lanjut Usia dan ODK :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Seksi Rehabilitasi Anak, Remaja, Lanjut Usia dan
<p > <h4 style="text-align: left; text-indent: 0.9in;"> ODK;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. menyiapkan bahan penyusunan perumusan kebijakan rehabilitasi sosial bagi Anak, Remaja dan Lansia 
<p > <h4 style="text-align: left; text-indent: 0.9in;">dan ODK;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. melaksanakan pengumpulan dan pengelolaan data PMKS anak, remaja, lanjut usia dan orang dengan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">kedisabilitasan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan pengoordinasian bimbingan dan rehabilitasi sosial bagi PMKS anak, remaja, lanjut usia 
<p > <h4 style="text-align: left; text-indent: 0.9in;">dan orang dengan kedisabilitasan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. menyiapkan bahan kerjasama dan kemitraan dalam rangka rehabilitasi sosial bagi PMKS anak, remaja, 
<p > <h4 style="text-align: left; text-indent: 0.9in;">lanjut usia dan orang dengan kedisabilitasan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Seksi Rehabilitasi Anak, 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Remaja, Lanjut Usia dan ODK;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 14</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Seksi Rehabilitasi Tuna Sosial dan Nafza mempunyai tugas pokok mempunyai tugas pokok menyiapkan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">bahan kebijakan operasional, pelaksanaan kebijakan serta pembinaan bagi rehabilitasi sosial bagi 
<p > <h4 style="text-align: left; text-indent: 0.9in;">tuna sosial dan nafza.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Seksi Rehabilitasi Tuna Sosial dan Nafza :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Seksi Rehabilitasi Tuna Sosial dan Nafza;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. melaksanakan penyiapan bahan kebijakan teknis di Seksi Rehabilitasi Tuna Sosial dan Nafza;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. melaksanakan pengumpulan dan pengelolaan data PMKS Tuna Sosial dan Nafza;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan pengoordinasian bimbingan dan rehabilitasi sosial bagi PMKS Tuna Sosial dan Nafza;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. menyiapkan bahan kerjasama dan kemitraan dalam rangka rehabilitasi sosial bagi PMKS Tuna 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Sosial dan Nafza;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Seksi Pengawasan
<p > <h4 style="text-align: left; text-indent: 0.9in;"> Ketenagakerjaan;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b> <h4 style="text-align: left; text-indent: 0.7in;">Bagian Ke lima : Bidang Perlindungan dan Jaminan Sosial</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 15</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Bidang Perlindungan dan Jaminan Sosial mempunyai tugas pokok mengoordinasikan perumusan bahan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">kebijakan, pelaksanaan kebijakan dan pembinaan di bidang perlindungan dan jaminan sosial.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Bidang Perlindungan dan Jaminan Sosial:</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. menyelenggarakan penyusunan rencana program kerja Bidang Perlindungan dan Jaminan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. menyelenggarakan penyusunan bahan kebijakan teknis pada Bidang Perlindungan dan Jaminan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. mngoordinasikan pengumpulan dan pengelolaan data fakir miskin;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan pengembangan jaminan dan perlindungan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. melaksanakan pemberian bimbingan teknis dan supervisi di bidang perlindungan dan jaminan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. menyelenggarakan penyiapan bahan pemberian ijin pengangkatan anak antar WNI;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan perumusan, pengkoordinasian dan pelakksanaan kebijakan penanggulangan bencana;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. menyelenggarakan kerjasama dan kemitraan pelaksanaan perlindungan dan jaminan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">i. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Bidang Perlindungan dan
<p > <h4 style="text-align: left; text-indent: 0.9in;"> Jaminan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">j. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">k. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">(3) Bidang Pelatihan, Perluasan Kesempatan Kerja dan Transmigrasi, membawahkan :</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. Seksi Perlindungan Sosial; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. Seksi Jaminan Sosial.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 16</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Seksi Perlindungan Sosial mempunyai tugas pokok mempunyai tugas pokok menyiapkan bahan
<p > <h4 style="text-align: left; text-indent: 0.9in;"> kebijakan operasional, pelaksanaan kebijakan serta pembinaan perlindungan sosial.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Seksi Perlindungan Sosial:</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Seksi Perlindungan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. menyusun bahan perumusan kebijakan di seksi perlindungan sosial bagi Penyandang Masalah 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Kesejahteraan Sosial (PMKS);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. menyusun bahan pelaksanaan kebijakan perlindungan sosial sosial bagi Penyandang Masalah 
<p > <h4 style="text-align: left; text-indent: 0.9in;">Kesejahteraan Sosial (PMKS);</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan pengoordinasian pemberian ijin pengangkatan anak antar WNI;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. melaksanakan penyiapan bahan kerjasama dan kemitraan pelaksanaan perlindungan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Seksi Perlindungan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p ><b><h4 style="text-align: left; text-indent: 0.7in;">Pasal 17</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(1) Seksi Jaminan Sosial mempunyai tugas pokok menyiapkan bahan kebijakan operasional, pelaksanaan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">kebijakan serta pembinaan penyelenggaraan jaminan sosial.</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;"></h4></p>
<p > <h4 style="text-align: left; text-indent: 0.5in;">(2) Rincian tugas Seksi Jaminan Sosial:</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">a. melaksanakan penyusunan rencana program kerja Seksi Jaminan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">b. menyelenggarakan penyusunan bahan perumusan kebijakan teknis, pedoman dan petunjuk teknis 
<p > <h4 style="text-align: left; text-indent: 0.9in;">penyelenggaraan Jaminan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">c. melaksanakan pengumpulan dan pengelolaan data fakir miskin tingkat Kota;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">d. melaksanakan pengembangan dan fasilitasi jaminan sosial bagi keluarga fakir miskin dan 
<p > <h4 style="text-align: left; text-indent: 0.9in;">korban bencana;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">e. melaksanakan penyiapan bahan kerjasama dan kemitraan dalam penyelenggaraan jaminan sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">f. melaksanakan pemantauan, evaluasi dan pelaporan yang berkaitan dengan Seksi Jaminan Sosial;</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">g. melaksanakan koordinasi dengan unit kerja terkait; dan</h4></p>
<p > <h4 style="text-align: left; text-indent: 0.7in;">h. melaksanakan tugas kedinasan lain sesuai dengan tugas dan fungsinya. </h4></p>
</div></div>
</div>
